# Избранное

## Список избранный предложений

GET http://localhost:5000/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImVtYWFpdzIyMjJsYUBtYWlsLnJ1IiwibmFtZSI6IlRFc3RVc2VyIiwiYXZhdGFyIjoiNTEzZDhiNTUtOTU3ZS00YzBkLWEyMDYtMThhOTFiZWNmODAyLnBuZyIsImlkIjoiNjcyMGY1NjE4NGRhM2VmYmM1NzBkNDY0IiwiaWF0IjoxNzMwMzg1NTc1LCJleHAiOjE3MzA1NTgzNzV9.I818C19VJ_1loJBBK3QLcbRXjkRUKKByeTcUteylnm4


###

## Добавить в избранное

POST http://localhost:5000/favorites/672048f4f74eed4cf40b9fc0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImVtYWFpdzIyMjJsYUBtYWlsLnJ1IiwibmFtZSI6IlRFc3RVc2VyIiwiYXZhdGFyIjoiNTEzZDhiNTUtOTU3ZS00YzBkLWEyMDYtMThhOTFiZWNmODAyLnBuZyIsImlkIjoiNjcyMGY1NjE4NGRhM2VmYmM1NzBkNDY0IiwiaWF0IjoxNzMwMzg1NTc1LCJleHAiOjE3MzA1NTgzNzV9.I818C19VJ_1loJBBK3QLcbRXjkRUKKByeTcUteylnm4


###

## Удалить из избранного

DELETE http://localhost:5000/favorites/672048f4f74eed4cf40b9fc0 HTTP/1.1
Authorization: Bearer Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImVtYWFpdzIyMjJsYUBtYWlsLnJ1IiwibmFtZSI6IlRFc3RVc2VyIiwiaXNQcm8iOnRydWUsImF2YXRhciI6ImRlZmF1bHQtYXZhdGFyLmpwZyIsImlkIjoiNjcyMGY1NjE4NGRhM2VmYmM1NzBkNDY0IiwiaWF0IjoxNzMwMzAzMzc5LCJleHAiOjE3MzA0NzYxNzl9.B3vwhnKHFTEXnFZdCGZp58A5DWMgcaLQGWxP0EWgjWQ

