# Пользователи
## Получить список пользователей
GET http://localhost:5000/users HTTP/1.1
Content-Type: application/json

###
## Создать пользователя
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "TEstUser",
  "email": "emaaiw21la@mail.ru@",
  "avatar": "1.sjpgs",
  "password": "string",
  "isPro": true
}
###
# Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "email@mail2.ru",
  "password": "string"
}

###
## Get avatar image in upload dir
GET http://localhost:5000/upload/avatar3.png HTTP/1.1
