# Пользователи
## Получить список пользователей
GET http://localhost:5000/users HTTP/1.1
Content-Type: application/json

###
## Создать пользователя
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "TEstUser",
  "email": "emaaiw222la@mail.ru",
  "password": "string",
  "isPro": true
}
###
# Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "email@mail2.ru",
  "password": "string"
}

###
## Get avatar image in upload dir
GET http://localhost:5000/upload/avatar3.png HTTP/1.1


###

## Отправить изображение

POST http://localhost:5000/users/66fc1dabd02a728f8aba063d/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< D:\Learn\HtmlAcademy\2160127-six-cities-8\upload\avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImVtYWlsQG1haWwyLnJ1IiwibmFtZSI6IlRFc3RVc2VyIiwiaXNQcm8iOnRydWUsImF2YXRhciI6IjEuaW1nIiwiaWQiOiI2NzBlOWNjY2NmYzgwMmViMzY3ZjgwODYiLCJpYXQiOjE3MzAxMjg0MDEsImV4cCI6MTczMDMwMTIwMX0.RvP1vZMY0vR3mskrqkn1SGoeFKOTMr-ZcshL56uOm1k

###
