# Предложения
## Получить список предложений
GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

###

# Создание предложения
## Создание предложения
POST  http://localhost:5000/offers/ HTTP/1.1
Content-Type: application/json

{
  "title": "test offer",
  "description": "test test",
  "createdDate": "2027-08-14T04:02:02.487Z",
  "city": "Cologne",
  "location": "52.370216,4.895168",
  "previewImage": "preview/2.jpg",
  "images": "foto/2.jpg,foto/3.jpg,foto/4.jpg,foto/5.jpg,foto/6.jpg,foto/7.jpg",
  "isPremium": false,
  "isFavorite": false,
  "rating": 3,
  "OfferTypeEnum": "apartment",
  "bedrooms": 1,
  "quests": 3,
  "price": 11000,
  "features": "Laptop friendly workspace,Baby seat,Washer,Towels,Fridge",
  "userId": "66fe928984d10f086922abba"

}
