# Уомментарии
## Получить список комментарией
GET http://localhost:5000/comments HTTP/1.1
Content-Type: application/json

###
# Количество по id пользователя
## Получить список комментарией
GET http://localhost:5000/comments/count/66fe928984d10f086922abbc HTTP/1.1
Content-Type: application/json

###
# Создание комментария
POST  http://localhost:5000/comments/ HTTP/1.1
Content-Type: application/json

{
  "comment": "test comment",
  "rating": 2,
  "offerId": "66fe928984d10f086922abbc",
  "userId": "66fe928984d10f086922abba",
  "date": "2023-02-16T20:21:16.614Z"
}
###
